### ISSUE TITLE
Anti-ND occasionally bugs weapons, causing them to not fire

### ISSUE THREAD

**Issue by ReddishRed** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#196]
See TItle

On occasion, and it seems random who gets it, the rifle will not get out of anti-ND and will not fire

**Comment by EM-Creations** [comment]
Need an example of the settings used for a mission where this has happened.

**Comment by ReddishRed** [comment]
class BLUFOR {
    time = 60;
    distance = 200;
};

class OPFOR {
    time = 60;
    distance = 200;
};

class INDFOR {
    time = 60;
    distance = 200;
};

class CIV {
    time = 60;
    distance = 200;
};

from bosnianboogaloo, where it bugged

**Comment by EM-Creations** [comment]
From looking at the code I can't see what could be causing this. I've raised this pull request: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/199

So that if we see this happen again, the logs could be checked to see if the code thinks its removing the event handlers or not, if we see nothing in the logs then we know the event handlers are not even being attempted to be removed, for some reason.

**Comment by PiZZAD0X** [comment]
Also cannot see where it is bugging out, but we can make it more safe by having a frequent check to see if the EH have been removed/time has already been elapsed... if anything we can just try and force take away the eventhandlers a couple times....

**Comment by PiZZAD0X** [comment]
New command in 2.10 is our salvation... https://community.bistudio.com/wiki/getEventHandlerInfo
This means we can query the active EHs for the units and remove when found, meaning we won't "miss" EHs being removed and not be caught in a subsequent check, which sounds like what is happening if it is random.
